# Generated by Django 5.1.4 on 2025-01-19 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='Category',
            new_name='category',
        ),
    ]
